=== Geeklog-GSoC/Repository-Plugin/public_html/xml/repository_listing.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.geeklog.com"
xmlns="http://www.geeklog.com"
elementFormDefault="qualified">


<xs:element name="repository">
  <xs:complexType>
    <xs:sequence>
    
<xs:element name="plugin">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="id" type="xs:integer"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="version" type="xs:string"/>
      <xs:element name="db" type="xs:integer"/>
      <xs:element name="dependencies" type="xs:string"/>
      <xs:element name="soft_dep" type="xs:string"/>
      <xs:element name="short_des" type="xs:string"/>
      <xs:element name="long_des" type="xs:string"/>
      <xs:element name="credits" type="xs:string"/>
      <xs:element name="vett" type="xs:integer"/>
      <xs:element name="downloads" type="xs:integer"/>
      <xs:element name="install" type="xs:integer"/>
      <xs:element name="state" type="xs:string"/>
      <xs:element name="ext" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== Geeklog-GSoC/Repository-Plugin/public_html/xml/sample_repository_listing.xml
<?xml version="1.0"?>

<repository
xmlns="http://www.geeklog.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.geeklog.com repository_listing.xsd">

<!-- Start Plugin List -->
    <plugin>
        <id>1</id>
	<name>Random Plugin</name>
	<version>1.0.11</version>
	<db>1</db>
	<dependencies>MyPlugin</dependencies>
	<soft_dep></soft_dep>
	<short_des>Nothing much to say</short_des>
	<long_des>Else here</long_des>
	<credits>Tim Patrick</credits>
	<vett>100</vett>
	<downloads>10014014</downloads>
	<install>1</install>
	<state>Stable</state>
	<ext>.zip</ext>
    </plugin>


<!-- End Plugin List -->

</repository>
